version: "3.7"
services:
  nginx:
    container_name: 'nginx'
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx/conf.d:/etc/nginx/conf.d
  jenkins:
    container_name: 'jenkins'
    restart: always
    image: jenkins
    volumes:
      - volumes/jenkins-data:/var/lib/mysql/data
  postgres:
    container_name: 'postgres'
    restart: always
    image: postgres
    volumes:
      - volumes/postgres-data:/var/lib/postgresql/data
  registry: # https://docs.docker.com/registry/deploying/ (Deploy your registry using a Compose file)
    container_name: 'registry'
    restart: always
    image: registry:2
    volumes:
      - volumes/registry-data:/var/lib/registry
  shoeser:
    container_name: 'shoeser'
    restart: always
    image: registry:5000/shoeser
    labels:
      - com.centurylinklabs.watchtower.enable=true
  # сервис автоперезапуска shoeser. После выпуска новой версии shoeser, он пересоздаст контейнер.
  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower:0.2.1
    command: --cleanup --label-enable
    restart: always
    volumes: # TODO согласовать директории с реестром registry (см. доку по v2tec/watchtower:0.2.1)
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/watchtower/config.json:/config.json:ro
